[project]
name = "ai-shopping-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nanuganti", email = "nanuganti@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai-shopping-assistant = "ai_shopping_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
